apiVersion: v1
kind: Pod
metadata:
  name: linux-pod
  labels:
    name: linux-pod
spec:
  containers:
  - name: alpine
    image: alpine
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 10; done"]