# -*- coding: utf-8 -*-
"""인공지능학교.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rzQsBQzqE5Yr5E-zP9pOg-QJduBM13Z4

함수와 클래스
"""

class Email:
    sender = ""

    def send_mail(self, recv, subject, contents) :
        print("From:\t" + self.sender)
        print("To:\t" + recv)
        print("Subject:\t" + subject)
        print("Contents")
        print(contents)
        print("-"*20)

e = Email()
e.sender = "bsmin0417@naver.com"
recv_list = ["s21030@gsm.hs.kr", "s21030@likelion.org"]

for recv in recv_list:
    e.send_mail(recv,"환영합니다", "함수와 클래스")

"""json파일 & open AP"""

import requests
import json

url = "	http://kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchDailyBoxOfficeList.json?key=89ea0da6eb4286cb92ef8c65983052c5&targetDt=20070226"

res = requests.get(url)
text = res.text
MD_json = json.loads(text)

# print(json.dumps(MD_json,indent=4,sort_keys=True))
# print(MD_json.keys())
# print(MD_json['boxOfficeResult'].keys())

for i in MD_json['boxOfficeResult']['dailyBoxOfficeList'] :
    print(i['rank'], i['rankOldAndNew'], i['movieCd'], i['movieNm'], i['salesAmt'])